title:
  en:           Page
  pt_BR:        Página

# Page options
icon:           file-o        # Font Awesome icon: http://fontawesome.io/icons
hide:           false         # Hide page from the panel
preview:        page          # page, parent, first-child, last-child

options:
  delete:       true          # Allow/disallow to delete a page
  preview:      true          # Show/hide the preview button in the sidebar
  status:       true          # Allow/disallow to change the status of a page
  template:     true          # Allow/disallow to change the template of a page
  update:       true          # Prevent editing of a page for all editors
  url:          true          # Allow/disallow to modify the URL of a page


# Subpages options
pages:
  add:          true          # Show/hide the add button
  hide:         false         # Hide subpages
  limit:        20            # Paginate displayed subpages
  max:          null          # Maximum number of subpages
  num:          null          # Numbering mode of visible subpages: default, zero and date
  sort:         null          # Sort subpages by field
  template:     default       # Restrict templates


# Files options
files:
  add:          true          # Show/hide the add button
  hide:         false         # Hide files in the panel
  max:          null          # Maximum number of files
  sanitize:     true          # Sanitizes uploaded filenames
  size:         false         # Limit the file size
  sortable:     true          # Enable sorting files by drag & drop
  type:         null          # Restrict panel users to upload other types
  height:       false         # Limit image height
  width:        false         # Limit image width
  fields:
    alt:        alt
    caption:    caption


# Fields options
fields:
  title:
    label:
      en:       Title
      pt_BR:    Título
    type:       title

  text:
    label:
      en:       Text
      pt_BR:    Conteúdo
    type:       textarea
